-- Основная таблица чатов
CREATE TABLE chat
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    title      VARCHAR(255)
);

ALTER TABLE chat
    OWNER TO postgres;

CREATE TABLE chat_entry
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id    BIGINT       NOT NULL REFERENCES chat (id) ON DELETE CASCADE,
    role       VARCHAR(20)  NOT NULL,
    content    TEXT         NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_chat_entry_chat_id_created_at
    ON chat_entry (chat_id, created_at);

-- =============================================
-- RAG (Retrieval-Augmented Generation) Tables
-- =============================================

-- Таблица загруженных документов
CREATE TABLE IF NOT EXISTS loaded_document
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename      VARCHAR(255) NOT NULL,
    content_hash  VARCHAR(64)  NOT NULL,
    document_type VARCHAR(10)  NOT NULL,
    chunk_count   INTEGER,
    source        VARCHAR(20)  NOT NULL,
    loaded_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT unique_document UNIQUE (filename, content_hash, source)
);

-- Индекс для быстрого поиска по имени файла
CREATE INDEX IF NOT EXISTS idx_loaded_documents_filename
    ON loaded_document (filename);
